# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobeverycommon.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jobEveryCommon(object):
    def setupUi(self, jobEveryCommon):
        jobEveryCommon.setObjectName("jobEveryCommon")
        jobEveryCommon.setWindowModality(QtCore.Qt.WindowModal)
        jobEveryCommon.resize(220, 320)
        jobEveryCommon.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(jobEveryCommon)
        self.centralwidget.setObjectName("centralwidget")
        self.job_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.job_text.setGeometry(QtCore.QRect(10, 55, 200, 50))
        self.job_text.setObjectName("job_text")
        self.lbl_tip = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tip.setGeometry(QtCore.QRect(10, 25, 60, 20))
        self.lbl_tip.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lbl_tip.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_tip.setObjectName("lbl_tip")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(170, 25, 20, 20))
        self.btn_add.setObjectName("btn_add")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(190, 25, 20, 20))
        self.btn_minus.setObjectName("btn_minus")
        self.tree_jobs = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_jobs.setGeometry(QtCore.QRect(10, 110, 200, 195))
        self.tree_jobs.setObjectName("tree_jobs")
        self.tree_jobs.headerItem().setText(0, "1")
        self.btn_mini = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mini.setGeometry(QtCore.QRect(30, 10, 15, 15))
        self.btn_mini.setStyleSheet("")
        self.btn_mini.setText("")
        self.btn_mini.setObjectName("btn_mini")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(10, 10, 15, 15))
        self.btn_close.setStyleSheet("")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.time_comb = QtWidgets.QComboBox(self.centralwidget)
        self.time_comb.setGeometry(QtCore.QRect(70, 25, 69, 22))
        self.time_comb.setObjectName("time_comb")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(70, 0, 60, 20))
        self.lbl_title.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.lbl_title.setText("")
        self.lbl_title.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_title.setObjectName("lbl_title")
        jobEveryCommon.setCentralWidget(self.centralwidget)

        self.retranslateUi(jobEveryCommon)
        QtCore.QMetaObject.connectSlotsByName(jobEveryCommon)

    def retranslateUi(self, jobEveryCommon):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_tip.setText(_translate("jobEveryCommon", "提醒时间:"))
        self.btn_add.setText(_translate("jobEveryCommon", "+"))
        self.btn_minus.setText(_translate("jobEveryCommon", "-"))
